<a href="https://colab.research.google.com/github/DhawalV1/Algorithmic_Trading_and_Quant_Strategies/blob/main/QOSF_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# prompt: write kronecker product for any number of matrix

import numpy as np

def kron(*matrices):
  """Computes the Kronecker product of multiple matrices.

  Args:
    *matrices: A sequence of NumPy arrays representing matrices.

  Returns:
    The Kronecker product of the input matrices.
  """
  result = np.array(1)  # Initialize with a scalar 1
  for matrix in matrices:
    result = np.kron(result, matrix)
  return result

# Example usage:
# matrix1 = np.array([[1, 2], [3, 4]])
# matrix2 = np.array([[5, 6], [7, 8]])
# matrix3 = np.array([[9, 10], [11, 12]])
# kronecker_prod = kronecker_product(matrix1, matrix2, matrix3)
# print(kronecker_prod)

In [51]:
def Hadamard():
    return np.array([[1,1],[1,-1]])/np.sqrt(2)

def identity():
    return np.array([[1,0],[0,1]])

def rz(theta):
    return np.array([[np.exp(theta*1j),0],[0,np.exp(-theta*1j)]])

zero = np.array([1,0])
one = np.array([0,1])

state = kron(zero,zero,zero)

In [59]:
(rz(np.pi)@one).round()

array([ 0.+0.j, -1.-0.j])

In [47]:
Hadamard()@zero

array([0.70710678, 0.70710678])

In [16]:
gate = kron(Hadamard(),identity(),identity())

In [33]:
zero.conj().T

array([1, 0])

In [17]:
new_state = gate @ state

In [19]:
def X():
    return np.array([[0,1],[1,0]])
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.70710678,
       0.        , 0.        , 0.        ])

In [34]:
CNOT = kron(np.outer(zero,zero),identity(),identity()) + kron(np.outer(one,one),identity(),X())

In [35]:
CNOT

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])

In [36]:
new_state = CNOT @ new_state

In [37]:
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.70710678, 0.        , 0.        ])

In [42]:
result = []

start = np.array(1)

for i in range(3):

  start = np.array(1)
  for j in range(3):
    if j == i:
      x = Hadamard()
    else:
      x = identity()
    start = kron(start,x)
  result.append(start)

for i in result:
  for j in i:
    print(j)



[0.5 0.  0.  0.  0.5 0.  0.  0. ]
[0.  0.5 0.  0.  0.  0.5 0.  0. ]
[0.  0.  0.5 0.  0.  0.  0.5 0. ]
[0.  0.  0.  0.5 0.  0.  0.  0.5]
[ 0.5  0.   0.   0.  -0.5 -0.  -0.  -0. ]
[ 0.   0.5  0.   0.  -0.  -0.5 -0.  -0. ]
[ 0.   0.   0.5  0.  -0.  -0.  -0.5 -0. ]
[ 0.   0.   0.   0.5 -0.  -0.  -0.  -0.5]
[0.5 0.  0.5 0.  0.  0.  0.  0. ]
[0.  0.5 0.  0.5 0.  0.  0.  0. ]
[ 0.5  0.  -0.5 -0.   0.   0.  -0.  -0. ]
[ 0.   0.5 -0.  -0.5  0.   0.  -0.  -0. ]
[0.  0.  0.  0.  0.5 0.  0.5 0. ]
[0.  0.  0.  0.  0.  0.5 0.  0.5]
[ 0.   0.  -0.  -0.   0.5  0.  -0.5 -0. ]
[ 0.   0.  -0.  -0.   0.   0.5 -0.  -0.5]
[0.5 0.5 0.  0.  0.  0.  0.  0. ]
[ 0.5 -0.5  0.  -0.   0.  -0.   0.  -0. ]
[0.  0.  0.5 0.5 0.  0.  0.  0. ]
[ 0.  -0.   0.5 -0.5  0.  -0.   0.  -0. ]
[0.  0.  0.  0.  0.5 0.5 0.  0. ]
[ 0.  -0.   0.  -0.   0.5 -0.5  0.  -0. ]
[0.  0.  0.  0.  0.  0.  0.5 0.5]
[ 0.  -0.   0.  -0.   0.  -0.   0.5 -0.5]


In [ ]:
circuit = np.zeros(32)

def x(arr,i):
