<a href="https://colab.research.google.com/github/DhawalV1/Algorithmic_Trading_and_Quant_Strategies/blob/main/qosf_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: write kronecker product for any number of matrix

import numpy as np

def kron(*matrices):
  """Computes the Kronecker product of multiple matrices.

  Args:
    *matrices: A sequence of NumPy arrays representing matrices.

  Returns:
    The Kronecker product of the input matrices.
  """
  result = np.array(1)  # Initialize with a scalar 1
  for matrix in matrices:
    result = np.kron(result, matrix)
  return result

# Example usage:
# matrix1 = np.array([[1, 2], [3, 4]])
# matrix2 = np.array([[5, 6], [7, 8]])
# matrix3 = np.array([[9, 10], [11, 12]])
# kronecker_prod = kronecker_product(matrix1, matrix2, matrix3)
# print(kronecker_prod)

In [ ]:
def Hadamard():
    return np.array([[1,1],[1,-1]])/np.sqrt(2)

def identity():
    return np.array([[1,0],[0,1]])

def rz(theta):
    return np.array([[np.exp(theta*1j),0],[0,np.exp(-theta*1j)]])

zero = np.array([1,0])
one = np.array([0,1])

state = kron(zero,zero,zero)

In [ ]:
(rz(np.pi)@one).round()

array([ 0.+0.j, -1.-0.j])

In [ ]:
Hadamard()@zero

array([0.70710678, 0.70710678])

In [ ]:
gate = kron(Hadamard(),identity(),identity())

In [ ]:
zero.conj().T

array([1, 0])

In [ ]:
new_state = gate @ state

In [ ]:
def X():
    return np.array([[0,1],[1,0]])
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.70710678,
       0.        , 0.        , 0.        ])

In [ ]:
CNOT = kron(np.outer(zero,zero),identity(),identity()) + kron(np.outer(one,one),identity(),X())

In [ ]:
CNOT

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
new_state = CNOT @ new_state

In [ ]:
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.70710678, 0.        , 0.        ])

In [ ]:
result = []

start = np.array(1)

for i in range(3):

  start = np.array(1)
  for j in range(3):
    if j == i:
      x = Hadamard()
    else:
      x = identity()
    start = kron(start,x)
  result.append(start)

for i in result:
  for j in i:
    print(j)



[0.5 0.  0.  0.  0.5 0.  0.  0. ]
[0.  0.5 0.  0.  0.  0.5 0.  0. ]
[0.  0.  0.5 0.  0.  0.  0.5 0. ]
[0.  0.  0.  0.5 0.  0.  0.  0.5]
[ 0.5  0.   0.   0.  -0.5 -0.  -0.  -0. ]
[ 0.   0.5  0.   0.  -0.  -0.5 -0.  -0. ]
[ 0.   0.   0.5  0.  -0.  -0.  -0.5 -0. ]
[ 0.   0.   0.   0.5 -0.  -0.  -0.  -0.5]
[0.5 0.  0.5 0.  0.  0.  0.  0. ]
[0.  0.5 0.  0.5 0.  0.  0.  0. ]
[ 0.5  0.  -0.5 -0.   0.   0.  -0.  -0. ]
[ 0.   0.5 -0.  -0.5  0.   0.  -0.  -0. ]
[0.  0.  0.  0.  0.5 0.  0.5 0. ]
[0.  0.  0.  0.  0.  0.5 0.  0.5]
[ 0.   0.  -0.  -0.   0.5  0.  -0.5 -0. ]
[ 0.   0.  -0.  -0.   0.   0.5 -0.  -0.5]
[0.5 0.5 0.  0.  0.  0.  0.  0. ]
[ 0.5 -0.5  0.  -0.   0.  -0.   0.  -0. ]
[0.  0.  0.5 0.5 0.  0.  0.  0. ]
[ 0.  -0.   0.5 -0.5  0.  -0.   0.  -0. ]
[0.  0.  0.  0.  0.5 0.5 0.  0. ]
[ 0.  -0.   0.  -0.   0.5 -0.5  0.  -0. ]
[0.  0.  0.  0.  0.  0.  0.5 0.5]
[ 0.  -0.   0.  -0.   0.  -0.   0.5 -0.5]


In [ ]:
circuit = np.zeros(32)

def x(arr,i):


In [3]:
from qiskit import QuantumCircuit
import numpy as np

# Define a function to replace an H gate with basis gates
def decompose_h():
    # H gate decomposition using RZ, SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)  # equivalent to Z gate in this context
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(np.pi, 0)
    return decomposed_circuit

# Define a function to replace an RX gate with basis gates
def decompose_rx(theta):
    # RX(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi/2, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(-np.pi/2, 0)
    return decomposed_circuit

# Define a function to replace an RY gate with basis gates
def decompose_ry(theta):
    # RY(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    return decomposed_circuit

# Define a function to transpile a full circuit from scratch
def custom_transpile(circuit):
    transpiled_circuit = QuantumCircuit(circuit.num_qubits)

    for instr, qargs, cargs in circuit.data:
        gate_name = instr.name
        qubit_index = [qubit.index for qubit in qargs]

        if gate_name == "h":
            # Decompose H gate
            decomposed_h = decompose_h()
            transpiled_circuit.compose(decomposed_h, qubit_index, inplace=True)

        elif gate_name == "rx":
            # Decompose RX gate
            theta = instr.params[0]
            decomposed_rx = decompose_rx(theta)
            transpiled_circuit.compose(decomposed_rx, qubit_index, inplace=True)

        elif gate_name == "ry":
            # Decompose RY gate
            theta = instr.params[0]
            decomposed_ry = decompose_ry(theta)
            transpiled_circuit.compose(decomposed_ry, qubit_index, inplace=True)

        elif gate_name == "rz":
            # RZ is already a basis gate
            transpiled_circuit.rz(instr.params[0], qubit_index[0])

        elif gate_name == "sx":
            # SX is already a basis gate
            transpiled_circuit.sx(qubit_index[0])

        elif gate_name == "x":
            # X is already a basis gate
            transpiled_circuit.x(qubit_index[0])

        elif gate_name == "cx":
            # CX is already a basis gate
            transpiled_circuit.cx(qubit_index[0], qubit_index[1])

        else:
            raise ValueError(f"Gate {gate_name} is not supported in the basis set.")

    return transpiled_circuit

# Example circuit with a mix of gates
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.rx(np.pi/3, 1)
qc.ry(np.pi/4, 0)

print("Original Circuit:")
print(qc)

# Transpile the circuit manually
transpiled_qc = custom_transpile(qc)

print("\nTranspiled Circuit:")
print(transpiled_qc)



Original Circuit:
     ┌───┐     ┌─────────┐
q_0: ┤ H ├──■──┤ Ry(π/4) ├
     └───┘┌─┴─┐├─────────┤
q_1: ─────┤ X ├┤ Rx(π/3) ├
          └───┘└─────────┘


<ipython-input-3-ff0c7321fc01>:38: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 2.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for instr, qargs, cargs in circuit.data:


AttributeError: 'Qubit' object has no attribute 'index'

In [7]:
for instr, qargs, cargs in qc.data:
  # print(instr.name,qargs,cargs)
  print(qargs)

[Qubit(QuantumRegister(2, 'q'), 0)]
[Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)]
[Qubit(QuantumRegister(2, 'q'), 1)]
[Qubit(QuantumRegister(2, 'q'), 0)]


<ipython-input-7-2848a71d0f71>:1: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 2.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for instr, qargs, cargs in qc.data:


In [12]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import XGate, YGate, ZGate

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.draw()

┌───┐     
q_0: ┤ H ├──■──
     └───┘┌─┴─┐
q_1: ─────┤ X ├
          └───┘

In [13]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import XGate, YGate, ZGate

def add_noise(circuit, alpha, beta):
    """
    Adds noise to a quantum circuit by introducing random Pauli operators
    after one-qubit and two-qubit gates with given probabilities.

    Parameters:
    - circuit (QuantumCircuit): The quantum circuit to which noise will be added.
    - p1 (float): Probability of adding a random Pauli gate after each one-qubit gate.
    - p2 (float): Probability of adding a random Pauli gate after each two-qubit gate.

    Returns:
    - QuantumCircuit: A new quantum circuit with added noise.
    """

    noisy_circuit = QuantumCircuit(circuit.num_qubits)

    # Dictionary of Pauli gates
    pauli_gates = [XGate(), YGate(), ZGate()]

    for instruction in circuit.data:
        gate = instruction.operation
        qubits = [qubit.index for qubit in instruction.qubits]

        # Append the original gate to the new circuit
        noisy_circuit.append(gate, qubits)

        # Determine if noise should be added
        if gate.num_qubits == 1:
            # Add noise after a one-qubit gate with probability p1
            if np.random.rand() < p1:
                pauli_gate = np.random.choice(pauli_gates)
                noisy_circuit.append(pauli_gate, [qubits[0]])

        elif gate.num_qubits == 2:
            # Add noise after a two-qubit gate with probability p2
            if np.random.rand() < p2:
                # Apply a random Pauli gate to each qubit in the two-qubit gate
                for qubit in qubits:
                    pauli_gate = np.random.choice(pauli_gates)
                    noisy_circuit.append(pauli_gate, [qubit])

    return noisy_circuit

add_noise(q)


TypeError: add_noise() missing 3 required positional arguments: 'circuit', 'alpha', and 'beta'

In [9]:
from qiskit import QuantumCircuit
import numpy as np

# Define a function to replace an H gate with basis gates
def decompose_h():
    # H gate decomposition using RZ, SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)  # equivalent to Z gate in this context
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(np.pi, 0)
    return decomposed_circuit

# Define a function to replace an RX gate with basis gates
def decompose_rx(theta):
    # RX(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi/2, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(-np.pi/2, 0)
    return decomposed_circuit

# Define a function to replace an RY gate with basis gates
def decompose_ry(theta):
    # RY(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    return decomposed_circuit

# Define a function to transpile a full circuit from scratch
def custom_transpile(circuit):
    transpiled_circuit = QuantumCircuit(circuit.num_qubits)

    # Update the loop to use operation, qubits, and clbits explicitly
    for instruction in circuit.data:
        instr = instruction.operation
        qargs = instruction.qubits
        gate_name = instr.name

        # Use find_bit to get the correct index for each qubit in qargs
        qubit_index = [circuit.find_bit(qubit).index for qubit in qargs]

        if gate_name == "h":
            # Decompose H gate
            decomposed_h = decompose_h()
            transpiled_circuit.compose(decomposed_h, qubit_index, inplace=True)

        elif gate_name == "rx":
            # Decompose RX gate
            theta = instr.params[0]
            decomposed_rx = decompose_rx(theta)
            transpiled_circuit.compose(decomposed_rx, qubit_index, inplace=True)

        elif gate_name == "ry":
            # Decompose RY gate
            theta = instr.params[0]
            decomposed_ry = decompose_ry(theta)
            transpiled_circuit.compose(decomposed_ry, qubit_index, inplace=True)

        elif gate_name == "rz":
            # RZ is already a basis gate
            transpiled_circuit.rz(instr.params[0], qubit_index[0])

        elif gate_name == "sx":
            # SX is already a basis gate
            transpiled_circuit.sx(qubit_index[0])

        elif gate_name == "x":
            # X is already a basis gate
            transpiled_circuit.x(qubit_index[0])

        elif gate_name == "cx":
            # CX is already a basis gate
            transpiled_circuit.cx(qubit_index[0], qubit_index[1])

        else:
            raise ValueError(f"Gate {gate_name} is not supported in the basis set.")

    return transpiled_circuit

# Example circuit with a mix of gates
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.rx(np.pi/3, 1)
qc.ry(np.pi/4, 0)

print("Original Circuit:")
print(qc)

# Transpile the circuit manually
transpiled_qc = custom_transpile(qc)

print("\nTranspiled Circuit:")
print(transpiled_qc)


Original Circuit:
     ┌───┐     ┌─────────┐
q_0: ┤ H ├──■──┤ Ry(π/4) ├
     └───┘┌─┴─┐├─────────┤
q_1: ─────┤ X ├┤ Rx(π/3) ├
          └───┘└─────────┘

Transpiled Circuit:
     ┌───────┐┌────┐┌───────┐      ┌───────┐ ┌────┐┌─────────┐┌────┐»
q_0: ┤ Rz(π) ├┤ √X ├┤ Rz(π) ├──■───┤ Rz(π) ├─┤ √X ├┤ Rz(π/4) ├┤ √X ├»
     └───────┘└────┘└───────┘┌─┴─┐┌┴───────┴┐├────┤├─────────┤├────┤»
q_1: ────────────────────────┤ X ├┤ Rz(π/2) ├┤ √X ├┤ Rz(π/3) ├┤ √X ├»
                             └───┘└─────────┘└────┘└─────────┘└────┘»
«                 
«q_0: ────────────
«     ┌──────────┐
«q_1: ┤ Rz(-π/2) ├
«     └──────────┘
