<a href="https://colab.research.google.com/github/DhawalV1/Algorithmic_Trading_and_Quant_Strategies/blob/main/qosf_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: write kronecker product for any number of matrix

import numpy as np

def kron(*matrices):
  """Computes the Kronecker product of multiple matrices.

  Args:
    *matrices: A sequence of NumPy arrays representing matrices.

  Returns:
    The Kronecker product of the input matrices.
  """
  result = np.array(1)  # Initialize with a scalar 1
  for matrix in matrices:
    result = np.kron(result, matrix)
  return result

# Example usage:
# matrix1 = np.array([[1, 2], [3, 4]])
# matrix2 = np.array([[5, 6], [7, 8]])
# matrix3 = np.array([[9, 10], [11, 12]])
# kronecker_prod = kronecker_product(matrix1, matrix2, matrix3)
# print(kronecker_prod)

In [ ]:
def Hadamard():
    return np.array([[1,1],[1,-1]])/np.sqrt(2)

def identity():
    return np.array([[1,0],[0,1]])

def rz(theta):
    return np.array([[np.exp(theta*1j),0],[0,np.exp(-theta*1j)]])

zero = np.array([1,0])
one = np.array([0,1])

state = kron(zero,zero,zero)

In [ ]:
(rz(np.pi)@one).round()

array([ 0.+0.j, -1.-0.j])

In [ ]:
Hadamard()@zero

array([0.70710678, 0.70710678])

In [ ]:
gate = kron(Hadamard(),identity(),identity())

In [ ]:
zero.conj().T

array([1, 0])

In [ ]:
new_state = gate @ state

In [ ]:
def X():
    return np.array([[0,1],[1,0]])
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.70710678,
       0.        , 0.        , 0.        ])

In [ ]:
CNOT = kron(np.outer(zero,zero),identity(),identity()) + kron(np.outer(one,one),identity(),X())

In [ ]:
CNOT

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
new_state = CNOT @ new_state

In [ ]:
new_state

array([0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.70710678, 0.        , 0.        ])

In [ ]:
result = []

start = np.array(1)

for i in range(3):

  start = np.array(1)
  for j in range(3):
    if j == i:
      x = Hadamard()
    else:
      x = identity()
    start = kron(start,x)
  result.append(start)

for i in result:
  for j in i:
    print(j)



[0.5 0.  0.  0.  0.5 0.  0.  0. ]
[0.  0.5 0.  0.  0.  0.5 0.  0. ]
[0.  0.  0.5 0.  0.  0.  0.5 0. ]
[0.  0.  0.  0.5 0.  0.  0.  0.5]
[ 0.5  0.   0.   0.  -0.5 -0.  -0.  -0. ]
[ 0.   0.5  0.   0.  -0.  -0.5 -0.  -0. ]
[ 0.   0.   0.5  0.  -0.  -0.  -0.5 -0. ]
[ 0.   0.   0.   0.5 -0.  -0.  -0.  -0.5]
[0.5 0.  0.5 0.  0.  0.  0.  0. ]
[0.  0.5 0.  0.5 0.  0.  0.  0. ]
[ 0.5  0.  -0.5 -0.   0.   0.  -0.  -0. ]
[ 0.   0.5 -0.  -0.5  0.   0.  -0.  -0. ]
[0.  0.  0.  0.  0.5 0.  0.5 0. ]
[0.  0.  0.  0.  0.  0.5 0.  0.5]
[ 0.   0.  -0.  -0.   0.5  0.  -0.5 -0. ]
[ 0.   0.  -0.  -0.   0.   0.5 -0.  -0.5]
[0.5 0.5 0.  0.  0.  0.  0.  0. ]
[ 0.5 -0.5  0.  -0.   0.  -0.   0.  -0. ]
[0.  0.  0.5 0.5 0.  0.  0.  0. ]
[ 0.  -0.   0.5 -0.5  0.  -0.   0.  -0. ]
[0.  0.  0.  0.  0.5 0.5 0.  0. ]
[ 0.  -0.   0.  -0.   0.5 -0.5  0.  -0. ]
[0.  0.  0.  0.  0.  0.  0.5 0.5]
[ 0.  -0.   0.  -0.   0.  -0.   0.5 -0.5]


In [ ]:
circuit = np.zeros(32)

def x(arr,i):


In [3]:
from qiskit import QuantumCircuit
import numpy as np

# Define a function to replace an H gate with basis gates
def decompose_h():
    # H gate decomposition using RZ, SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)  # equivalent to Z gate in this context
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(np.pi, 0)
    return decomposed_circuit

# Define a function to replace an RX gate with basis gates
def decompose_rx(theta):
    # RX(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi/2, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(-np.pi/2, 0)
    return decomposed_circuit

# Define a function to replace an RY gate with basis gates
def decompose_ry(theta):
    # RY(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    return decomposed_circuit

# Define a function to transpile a full circuit from scratch
def custom_transpile(circuit):
    transpiled_circuit = QuantumCircuit(circuit.num_qubits)

    for instr, qargs, cargs in circuit.data:
        gate_name = instr.name
        qubit_index = [qubit.index for qubit in qargs]

        if gate_name == "h":
            # Decompose H gate
            decomposed_h = decompose_h()
            transpiled_circuit.compose(decomposed_h, qubit_index, inplace=True)

        elif gate_name == "rx":
            # Decompose RX gate
            theta = instr.params[0]
            decomposed_rx = decompose_rx(theta)
            transpiled_circuit.compose(decomposed_rx, qubit_index, inplace=True)

        elif gate_name == "ry":
            # Decompose RY gate
            theta = instr.params[0]
            decomposed_ry = decompose_ry(theta)
            transpiled_circuit.compose(decomposed_ry, qubit_index, inplace=True)

        elif gate_name == "rz":
            # RZ is already a basis gate
            transpiled_circuit.rz(instr.params[0], qubit_index[0])

        elif gate_name == "sx":
            # SX is already a basis gate
            transpiled_circuit.sx(qubit_index[0])

        elif gate_name == "x":
            # X is already a basis gate
            transpiled_circuit.x(qubit_index[0])

        elif gate_name == "cx":
            # CX is already a basis gate
            transpiled_circuit.cx(qubit_index[0], qubit_index[1])

        else:
            raise ValueError(f"Gate {gate_name} is not supported in the basis set.")

    return transpiled_circuit

# Example circuit with a mix of gates
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.rx(np.pi/3, 1)
qc.ry(np.pi/4, 0)

print("Original Circuit:")
print(qc)

# Transpile the circuit manually
transpiled_qc = custom_transpile(qc)

print("\nTranspiled Circuit:")
print(transpiled_qc)



Original Circuit:
     ┌───┐     ┌─────────┐
q_0: ┤ H ├──■──┤ Ry(π/4) ├
     └───┘┌─┴─┐├─────────┤
q_1: ─────┤ X ├┤ Rx(π/3) ├
          └───┘└─────────┘


<ipython-input-3-ff0c7321fc01>:38: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 2.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for instr, qargs, cargs in circuit.data:


AttributeError: 'Qubit' object has no attribute 'index'

In [7]:
for instr, qargs, cargs in qc.data:
  # print(instr.name,qargs,cargs)
  print(qargs)

[Qubit(QuantumRegister(2, 'q'), 0)]
[Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)]
[Qubit(QuantumRegister(2, 'q'), 1)]
[Qubit(QuantumRegister(2, 'q'), 0)]


<ipython-input-7-2848a71d0f71>:1: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 2.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for instr, qargs, cargs in qc.data:


In [46]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import XGate, YGate, ZGate

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.draw()

┌───┐     
q_0: ┤ H ├──■──
     └───┘┌─┴─┐
q_1: ─────┤ X ├
          └───┘

In [43]:
get_random_pauli_gate = np.random.choice([XGate(), YGate(), ZGate()])

ValueError: a must be 1-dimensional

In [41]:
get_random_pauli_gate = np.random.choice([XGate(), YGate(), ZGate()])

0.6

In [56]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import XGate, YGate, ZGate

def add_noise(circuit, p1, p2):
    """
    Adds noise to a quantum circuit by introducing random Pauli operators
    after one-qubit and two-qubit gates with given probabilities.

    Parameters:
    - circuit (QuantumCircuit): The quantum circuit to which noise will be added.
    - p1 (float): Probability of adding a random Pauli gate after each one-qubit gate.
    - p2 (float): Probability of adding a random Pauli gate after each two-qubit gate.

    Returns:
    - QuantumCircuit: A new quantum circuit with added noise.
    """

    noisy_circuit = QuantumCircuit(circuit.num_qubits)

    # Lambda function to pick a random Pauli gate
    error_gate = [XGate(), YGate(), ZGate()]

    for instruction in circuit.data:
        gate = instruction.operation
        qubits = [circuit.find_bit(qubit).index for qubit in instruction.qubits]

        # Append the original gate to the new circuit
        noisy_circuit.append(gate, qubits)

        # Determine if noise should be added
        if gate.num_qubits == 1:
            # Add noise after a one-qubit gate with probability p1
            if np.random.rand() < p1:
                pauli_gate = np.random.choice([0,1,2])
                noisy_circuit.append(error_gate[pauli_gate],[qubits[0]])

        elif gate.num_qubits == 2:
            # Add noise after a two-qubit gate with probability p2
            if np.random.rand() < p2:
                # Apply a random Pauli gate to each qubit in the two-qubit gate
                for qubit in qubits:
                    pauli_gate = np.random.choice([0,1,2])
                    noisy_circuit.append(error_gate[pauli_gate], [qubit])

    return noisy_circuit

noisy = add_noise(qc, 0.5, 0.5)
noisy.draw()


┌───┐┌───┐     
q_0: ┤ H ├┤ Z ├──■──
     └───┘└───┘┌─┴─┐
q_1: ──────────┤ X ├
               └───┘

In [57]:
from qiskit import QuantumCircuit
import numpy as np

# Define a function to replace an H gate with basis gates
def decompose_h():
    # H gate decomposition using RZ, SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)  # equivalent to Z gate in this context
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(np.pi, 0)
    return decomposed_circuit

# Define a function to replace an RX gate with basis gates
def decompose_rx(theta):
    # RX(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi/2, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(-np.pi/2, 0)
    return decomposed_circuit

# Define a function to replace an RY gate with basis gates
def decompose_ry(theta):
    # RY(theta) decomposition using RZ and SX
    decomposed_circuit = QuantumCircuit(1)
    decomposed_circuit.rz(np.pi, 0)
    decomposed_circuit.sx(0)
    decomposed_circuit.rz(theta, 0)
    decomposed_circuit.sx(0)
    return decomposed_circuit

# Define a function to transpile a full circuit from scratch
def custom_transpile(circuit):
    transpiled_circuit = QuantumCircuit(circuit.num_qubits)

    # Update the loop to use operation, qubits, and clbits explicitly
    for instruction in circuit.data:
        instr = instruction.operation
        qargs = instruction.qubits
        gate_name = instr.name

        # Use find_bit to get the correct index for each qubit in qargs
        qubit_index = [circuit.find_bit(qubit).index for qubit in qargs]

        if gate_name == "h":
            # Decompose H gate
            decomposed_h = decompose_h()
            transpiled_circuit.compose(decomposed_h, qubit_index, inplace=True)

        elif gate_name == "rx":
            # Decompose RX gate
            theta = instr.params[0]
            decomposed_rx = decompose_rx(theta)
            transpiled_circuit.compose(decomposed_rx, qubit_index, inplace=True)

        elif gate_name == "ry":
            # Decompose RY gate
            theta = instr.params[0]
            decomposed_ry = decompose_ry(theta)
            transpiled_circuit.compose(decomposed_ry, qubit_index, inplace=True)

        elif gate_name == "rz":
            # RZ is already a basis gate
            transpiled_circuit.rz(instr.params[0], qubit_index[0])

        elif gate_name == "sx":
            # SX is already a basis gate
            transpiled_circuit.sx(qubit_index[0])

        elif gate_name == "x":
            # X is already a basis gate
            transpiled_circuit.x(qubit_index[0])

        elif gate_name == "cx":
            # CX is already a basis gate
            transpiled_circuit.cx(qubit_index[0], qubit_index[1])

        else:
            raise ValueError(f"Gate {gate_name} is not supported in the basis set.")

    return transpiled_circuit

# Example circuit with a mix of gates
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.rx(np.pi/3, 1)
qc.ry(np.pi/4, 0)

print("Original Circuit:")
print(qc)

# Transpile the circuit manually
transpiled_qc = custom_transpile(qc)

print("\nTranspiled Circuit:")
print(transpiled_qc)


Original Circuit:
     ┌───┐     ┌─────────┐
q_0: ┤ H ├──■──┤ Ry(π/4) ├
     └───┘┌─┴─┐├─────────┤
q_1: ─────┤ X ├┤ Rx(π/3) ├
          └───┘└─────────┘

Transpiled Circuit:
     ┌───────┐┌────┐┌───────┐      ┌───────┐ ┌────┐┌─────────┐┌────┐»
q_0: ┤ Rz(π) ├┤ √X ├┤ Rz(π) ├──■───┤ Rz(π) ├─┤ √X ├┤ Rz(π/4) ├┤ √X ├»
     └───────┘└────┘└───────┘┌─┴─┐┌┴───────┴┐├────┤├─────────┤├────┤»
q_1: ────────────────────────┤ X ├┤ Rz(π/2) ├┤ √X ├┤ Rz(π/3) ├┤ √X ├»
                             └───┘└─────────┘└────┘└─────────┘└────┘»
«                 
«q_0: ────────────
«     ┌──────────┐
«q_1: ┤ Rz(-π/2) ├
«     └──────────┘


In [60]:
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

In [102]:
# Set up six different observables.
from qiskit.quantum_info import SparsePauliOp

observables_labels = ["IZIIIIII"]
observables = [SparsePauliOp(label) for label in observables_labels]

In [ ]:
pip install qiskit_ibm_runtime

In [65]:
from qiskit_ibm_runtime import QiskitRuntimeService

# If you did not previously save your credentials, use the following line instead:
service = QiskitRuntimeService(channel="ibm_quantum", token="2e1b3eb3e672ac4571fddd2dc631f8876fd09fb538c9179a2e054748696c04d27851088e6ec5300cbff17e357a0f9235d0cbe16db1966947e2687c5dd4cd80dc")
# service = QiskitRuntimeService()

backend = service.least_busy(simulator=False, operational=True)

# Convert to an ISA circuit and layout-mapped observables.
pm = generate_preset_pass_manager(backend=backend, optimization_level=1)
isa_circuit = pm.run(qc)

isa_circuit.draw(idle_wires=False)

global phase: π/2
          ┌────────┐ ┌────┐          ┌──────┐ ┌────────┐ ┌────┐┌─────────┐»
q_0 -> 0 ─┤ Rz(-π) ├─┤ √X ├──────────┤1     ├─┤ Rz(-π) ├─┤ √X ├┤ Rz(π/4) ├»
         ┌┴────────┴┐├────┤┌────────┐│  Ecr │┌┴────────┴┐├────┤├─────────┤»
q_1 -> 1 ┤ Rz(-π/2) ├┤ √X ├┤ Rz(-π) ├┤0     ├┤ Rz(5π/6) ├┤ √X ├┤ Rz(π/2) ├»
         └──────────┘└────┘└────────┘└──────┘└──────────┘└────┘└─────────┘»
«         ┌────┐
«q_0 -> 0 ┤ √X ├
«         └────┘
«q_1 -> 1 ──────
«

In [ ]:
pip install pylatexenc

In [71]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import SparsePauliOp
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import EstimatorV2 as Estimator

def qft(circuit, n):
    """Apply the Quantum Fourier Transform to the first n qubits in the circuit."""
    for j in range(n):
        circuit.h(j)
        for k in range(j + 1, n):
            circuit.cp(np.pi / 2 ** (k - j), k, j)  # Controlled phase rotation

    # Reverse qubit order to complete QFT
    for i in range(n // 2):
        circuit.swap(i, n - i - 1)

def inverse_qft(circuit, n):
    """Apply the inverse Quantum Fourier Transform to the first n qubits in the circuit."""
    # Reverse the qubit order
    for i in range(n // 2):
        circuit.swap(i, n - i - 1)

    # Apply inverse QFT operations
    for j in range(n - 1, -1, -1):
        for k in range(j - 1, -1, -1):
            circuit.cp(-np.pi / 2 ** (j - k), j, k)  # Controlled phase rotation
        circuit.h(j)

def quantum_sum(a, b):
    """
    Quantum addition of two integers using the Draper adder algorithm.

    Parameters:
    - a (int): First integer to add.
    - b (int): Second integer to add.

    Returns:
    - QuantumCircuit: The circuit that adds a and b.
    """
    # Determine the number of qubits required
    n = max(a.bit_length(), b.bit_length()) + 1  # +1 to handle overflow

    # Create a quantum circuit with 2n qubits (n for each number)
    circuit = QuantumCircuit(2 * n)

    # Initialize the qubits to represent the binary forms of a and b
    # For number `a` in the first n qubits
    for i in range(n):
        if (a >> i) & 1:
            circuit.x(i)

    # For number `b` in the second n qubits
    for i in range(n):
        if (b >> i) & 1:
            circuit.x(i + n)

    # Apply QFT to the first register (where `a` is stored)
    qft(circuit, n)

    # Add the values of the second register (`b`) to the first register using controlled-phase gates
    for i in range(n):
        for j in range(i + 1):
            if (b >> j) & 1:
                circuit.cp(np.pi / 2 ** (i - j), j + n, i)

    # Apply inverse QFT to the first register to get the sum
    inverse_qft(circuit, n)

    # Measure the result from the first n qubits
    # circuit.measure_all()

    return circuit

# Example: Adding 3 + 5
a = 3
b = 5
adder_circuit = quantum_sum(a, b)

# # Simulate the circuit
# simulator = Aer.get_backend('aer_simulator')
# transpiled_circuit = transpile(adder_circuit, simulator)
# qobj = assemble(transpiled_circuit)
# results = simulator.run(qobj).result()
# counts = results.get_counts()

# print("Quantum Addition Result:")
# print(counts)


In [108]:
from qiskit_ibm_runtime import QiskitRuntimeService

# If you did not previously save your credentials, use the following line instead:
service = QiskitRuntimeService(channel="ibm_quantum", token="2e1b3eb3e672ac4571fddd2dc631f8876fd09fb538c9179a2e054748696c04d27851088e6ec5300cbff17e357a0f9235d0cbe16db1966947e2687c5dd4cd80dc")
# service = QiskitRuntimeService()

backend = service.least_busy(simulator=False, operational=True)

# Convert to an ISA circuit and layout-mapped observables.
pm = generate_preset_pass_manager(backend=backend, optimization_level=3)
isa_circuit = pm.run(adder_circuit)

isa_circuit.draw(idle_wires=False)

global phase: 0.29452
             ┌───┐                                                      »
q_4 -> 56 ───┤ X ├──────────────────────────────────────────────────────»
          ┌──┴───┴──┐                                                   »
q_3 -> 57 ┤ Rz(π/2) ├───────────────────────────────────────────────────»
          ├─────────┤    ┌────┐   ┌────────────┐┌──────┐                »
q_0 -> 58 ┤ Rz(π/2) ├────┤ √X ├───┤ Rz(2.1218) ├┤0     ├────────────────»
          └──┬───┬──┘ ┌──┴────┴──┐└────────────┘│  Ecr │┌────────┐┌────┐»
q_1 -> 59 ───┤ X ├────┤ Rz(-π/2) ├──────────────┤1     ├┤ Rz(-π) ├┤ √X ├»
          ┌──┴───┴───┐└──┬────┬──┘ ┌─────────┐  └──────┘└────────┘└────┘»
q_6 -> 60 ┤ Rz(-π/2) ├───┤ √X ├────┤ Rz(π/2) ├──────────────────────────»
          └──┬───┬───┘┌──┴────┴──┐ └─────────┘                          »
q_2 -> 71 ───┤ X ├────┤ Rz(-π/2) ├──────────────────────────────────────»
             └───┘    └──────────┘                                      »
«                                                                         »
«q_4 -> 56 ───────────────────────────────────────────────────────────────»
«                                                                         »
«q_3 -> 57 ───────────────────────────────────────────────────────────────»
«                            ┌──────┐   ┌───┐   ┌────────────┐            »
«q_0 -> 58 ──────────────────┤0     ├───┤ X ├───┤ Rz(2.9072) ├────────────»
«          ┌──────────┐┌────┐│  Ecr │┌──┴───┴──┐└───┬────┬───┘┌──────────┐»
«q_1 -> 59 ┤ Rz(3π/4) ├┤ √X ├┤1     ├┤ Rz(π/4) ├────┤ √X ├────┤ Rz(-π/2) ├»
«          └──────────┘└────┘└──────┘└─────────┘    └────┘    └──────────┘»
«q_6 -> 60 ───────────────────────────────────────────────────────────────»
«                                                                         »
«q_2 -> 71 ───────────────────────────────────────────────────────────────»
«                                                                         »
«                                                                           »
«q_4 -> 56 ─────────────────────────────────────────────────────────────────»
«                                                                           »
«q_3 -> 57 ─────────────────────────────────────────────────────────────────»
«          ┌──────┐                                  ┌──────┐     ┌───┐     »
«q_0 -> 58 ┤0     ├──────────────────────────────────┤0     ├─────┤ X ├─────»
«          │      │                                  │      │     └───┘     »
«q_1 -> 59 ┤      ├──────────────────────────────────┤      ├───────────────»
«          │  Ecr │                                  │  Ecr │               »
«q_6 -> 60 ┤      ├──────────────────────────────────┤      ├───────────────»
«          │      │┌────────┐┌────┐┌──────────┐┌────┐│      │┌─────────────┐»
«q_2 -> 71 ┤1     ├┤ Rz(-π) ├┤ √X ├┤ Rz(7π/8) ├┤ √X ├┤1     ├┤ Rz(-1.6535) ├»
«          └──────┘└────────┘└────┘└──────────┘└────┘└──────┘└─────────────┘»
«                                                                           »
«q_4 -> 56 ─────────────────────────────────────────────────────────────────»
«                       ┌──────┐                                    ┌──────┐»
«q_3 -> 57 ─────────────┤0     ├────────────────────────────────────┤0     ├»
«          ┌───────────┐│  Ecr │┌────────┐┌────┐┌────────────┐┌────┐│  Ecr │»
«q_0 -> 58 ┤ Rz(-3π/8) ├┤1     ├┤ Rz(-π) ├┤ √X ├┤ Rz(15π/16) ├┤ √X ├┤1     ├»
«          └───────────┘└──────┘└────────┘└────┘└────────────┘└────┘└──────┘»
«q_1 -> 59 ─────────────────────────────────────────────────────────────────»
«                                                                           »
«q_6 -> 60 ─────────────────────────────────────────────────────────────────»
«                                                                           »
«q_2 -> 71 ─────────────────────────────────────────────────────────────────»
«                                                                           »


In [100]:
isa_circuit.depth()


199

In [84]:
pip install qiskit-aer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 81.1 MB/s eta 0:00:00


In [94]:
from qiskit.providers.basic_provider import BasicSimulator

In [109]:
# Construct the Estimator instance.
from qiskit_ibm_runtime import EstimatorV2 as Estimator

estimator = Estimator(mode=backend)
estimator.options.resilience_level = 1
estimator.options.default_shots = 1000

mapped_observables = [
    observable.apply_layout(isa_circuit.layout) for observable in observables
]

# One pub, with one circuit to run against five different observables.
job = estimator.run([(isa_circuit, mapped_observables)])

# Use the job ID to retrieve your job data later
print(f">>> Job ID: {job.job_id()}")

>>> Job ID: cwfv8hj543p000863h80


In [110]:
# This is the result of the entire submission.  You submitted one Pub,
# so this contains one inner result (and some metadata of its own).
job_result = job.result()

# This is the result from our single pub, which had six observables,
# so contains information on all six.
pub_result = job.result()[0]

In [106]:

# Use the following code instead if you want to run on a simulator:

from qiskit_ibm_runtime.fake_provider import FakeAlmadenV2
backend = FakeAlmadenV2()
estimator = Estimator(backend)

# Convert to an ISA circuit and layout-mapped observables.

pm = generate_preset_pass_manager(backend=backend, optimization_level=1)
isa_circuit = pm.run(qc)
mapped_observables = [
    observable.apply_layout(isa_circuit.layout) for observable in [SparsePauliOp(['IZ'],
               coeffs=[1.+0.j])]
]

job = estimator.run([(isa_circuit, mapped_observables)])
result = job.result()

# This is the result of the entire submission.  You submitted one Pub,
# so this contains one inner result (and some metadata of its own).

job_result = job.result()

# This is the result from our single pub, which had five observables,
# so contains information on all five.

pub_result = job.result()[0]

/usr/local/lib/python3.10/dist-packages/qiskit_ibm_runtime/fake_provider/fake_backend.py:467: RuntimeWarning: Aer not found, using qiskit.BasicSimulator and no noise.
  warnings.warn(


In [105]:
observables

[SparsePauliOp(['IZIIIIII'],
               coeffs=[1.+0.j])]

In [ ]:
import numpy as np
from qiskit import QuantumCircuit, Aer, transpile, assemble, execute
from qiskit.circuit.library import XGate, YGate, ZGate

# Quantum Fourier Transform and Inverse QFT Functions
def qft(circuit, n):
    for j in range(n):
        circuit.h(j)
        for k in range(j + 1, n):
            circuit.cp(np.pi / 2 ** (k - j), k, j)
    for i in range(n // 2):
        circuit.swap(i, n - i - 1)

def inverse_qft(circuit, n):
    for i in range(n // 2):
        circuit.swap(i, n - i - 1)
    for j in range(n - 1, -1, -1):
        for k in range(j - 1, -1, -1):
            circuit.cp(-np.pi / 2 ** (j - k), j, k)
        circuit.h(j)

# Draper Quantum Addition Circuit
def quantum_sum(a, b):
    n = max(a.bit_length(), b.bit_length()) + 1
    circuit = QuantumCircuit(2 * n)
    for i in range(n):
        if (a >> i) & 1:
            circuit.x(i)
    for i in range(n):
        if (b >> i) & 1:
            circuit.x(i + n)
    qft(circuit, n)
    for i in range(n):
        for j in range(i + 1):
            if (b >> j) & 1:
                circuit.cp(np.pi / 2 ** (i - j), j + n, i)
    inverse_qft(circuit, n)
    circuit.measure_all()
    return circuit

# Add Noise to Circuit
def add_noise(circuit, p1, p2):
    noisy_circuit = QuantumCircuit(circuit.num_qubits)
    get_random_pauli_gate = lambda: np.random.choice([XGate(), YGate(), ZGate()])
    for instruction in circuit.data:
        gate = instruction.operation
        qubits = [circuit.find_bit(qubit).index for qubit in instruction.qubits]
        noisy_circuit.append(gate, qubits)
        if gate.num_qubits == 1 and np.random.rand() < p1:
            noisy_circuit.append(get_random_pauli_gate(), [qubits[0]])
        elif gate.num_qubits == 2 and np.random.rand() < p2:
            for qubit in qubits:
                noisy_circuit.append(get_random_pauli_gate(), [qubit])
    return noisy_circuit

# Transpile, Add Noise, and Simulate with Different Noise Levels
def simulate_quantum_sum_with_noise(a, b, p1, p2):
    qc = quantum_sum(a, b)
    noisy_qc = add_noise(qc, p1, p2)
    simulator = Aer.get_backend('aer_simulator')
    transpiled_circuit = transpile(noisy_qc, simulator)
    qobj = assemble(transpiled_circuit)
    result = simulator.run(qobj).result()
    counts = result.get_counts()
    return counts

# Experiment with Varying Noise Levels
a, b = 3, 5
for p1, p2 in [(0.05, 0.1), (0.1, 0.2), (0.15, 0.3)]:
    print(f"Noise Levels - One-qubit: {p1}, Two-qubit: {p2}")
    result_counts = simulate_quantum_sum_with_noise(a, b, p1, p2)
    print("Result Counts:", result_counts)
    print("\n")
